CusExperience/Entities/OrgSub.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace CusExperience.Entities
{
    public class OrgSub
    {

        [DataMember]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long OrgSubID { get; set; }

        [Required]
        public string RegisteredName { get; set; }

        [Required]
        public string RegisteredNumber { get; set; }

        [Required]
        public string BrandName { get; set; }

        [Required]
        public string BrandWebsite { get; set; }

        [Required]
        public string Industry { get; set; }

        public string Address { get; set; }

        public string GoogleMapsAddress { get; set; }

        [Required]
        public string Country { get; set; }

        [Required]
        public string State { get; set; }

        [Required]
        public string City { get; set; }

        public string FrontImage { get; set; }

        public string LogoImage { get; set; }

        public string PhoneNumber { get; set; }

        public string EmailAddress { get; set; }

        public virtual OrgSub parentOrgSub { get; set; }

        public virtual List<Touchpoint> TouchPoints { get; set; } 

    }
}

CusExperience/Controllers/OrgSubController.cs
using CusExperience.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using CusExperience.CusExperienceService;
using CusExperience.Entities;

namespace CusExperience.Controllers
{
    public class OrgSubController : Controller
    {
        OrgSubRepositoryClient oRep = new OrgSubRepositoryClient();
        UserRepositoryClient uRep = new UserRepositoryClient();

        public ActionResult Index()
        {
            try
            {
                if (uRep.isSuperAdministrator(User.Identity.GetUserId()))
                {
                    return View("Index", oRep.GetOrgSubs(User.Identity.GetUserId()));
                }
                else if (uRep.isAdministrator(User.Identity.GetUserId()))
                {
                    return RedirectToAction("Detail", "OrgSub", new { id = uRep.GetCurrentUser(User.Identity.GetUserId()).OrgSub.OrgSubID });
                }
                return View("UnAuthorized");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult Hierarchy(string id)
        {
            try
            {
                long orgSubId = 0;
                if (!long.TryParse(id, out orgSubId))
                    return View("Error");
                if (uRep.isSuperAdministrator(User.Identity.GetUserId()))
                {
                    return View(oRep.GetOrgSub(orgSubId, User.Identity.GetUserId()));
                }
                return View("UnAuthorized");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult Create(string id)
        {
            try
            {
                if (uRep.isSuperAdministrator(User.Identity.GetUserId()))
                {
                    if(string.IsNullOrEmpty(id))
                        return View();
                    else
                    {
                         long parentOrgSubID = 0;
                         if (!long.TryParse(id, out parentOrgSubID))
                             return View("Error");

                         OrgSub parentOrgSub = oRep.GetOrgSub(parentOrgSubID, User.Identity.GetUserId());
                         ViewBag.OrgSubName = !string.IsNullOrEmpty(parentOrgSub.ParentOrgSubName) ? parentOrgSub.ParentOrgSubName + " > " + parentOrgSub.RegisteredName : parentOrgSub.RegisteredName;

                         OrgSub orgSub = oRep.GetNewOrgSub(parentOrgSubID,User.Identity.GetUserId());
                         return View(orgSub);
                    }
                }
                return View("UnAuthorized");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult CreateSub(string id)
        {
            try
            {
                if (uRep.isSuperAdministrator(User.Identity.GetUserId()))
                {
                    if (string.IsNullOrEmpty(id))
                        return View();
                    else
                    {
                        long parentOrgSubID = 0;
                        if (!long.TryParse(id, out parentOrgSubID))
                            return View("Error");

                        OrgSub parentOrgSub = oRep.GetOrgSub(parentOrgSubID, User.Identity.GetUserId());
                        ViewBag.OrgSubName = !string.IsNullOrEmpty(parentOrgSub.ParentOrgSubName) ? parentOrgSub.ParentOrgSubName + " > " + parentOrgSub.RegisteredName : parentOrgSub.RegisteredName;

                        OrgSub orgSub = oRep.GetNewOrgSub(parentOrgSubID, User.Identity.GetUserId());
                        return View(orgSub);
                    }
                }
                return View("UnAuthorized");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult Detail(string id)
        {
            try
            {
                int orgSubID = Convert.ToInt32(id);
               
                if (uRep.isSuperAdministrator(User.Identity.GetUserId()))
                {
                    OrgSub orgSub = oRep.GetOrgSub(orgSubID, User.Identity.GetUserId());

                    if (orgSub == null)
                        return View("Error");

                    ViewBag.OrgSubName = !string.IsNullOrEmpty(orgSub.ParentOrgSubName) ? orgSub.ParentOrgSubName + " > " + orgSub.RegisteredName : orgSub.RegisteredName;
                    return View("Detail-Admin", orgSub);
                }
                else if (uRep.isAdministrator(User.Identity.GetUserId()))
                {
                    OrgSub orgSub = oRep.GetOrgSub(orgSubID, User.Identity.GetUserId());
                    
                    if(orgSub == null)
                        return View("Error");

                    ViewBag.OrgSubName = !string.IsNullOrEmpty(orgSub.ParentOrgSubName) ? orgSub.ParentOrgSubName + " > " + orgSub.RegisteredName : orgSub.RegisteredName;

                    return View("Detail", orgSub);
                }
                return View("UnAuthorized");
            }
            catch (Exception ex)
            {
                if (ex is UnauthorizedAccessException)
                    return View("UnAuthorized");
                return View("Error");
            }
        }

        public ActionResult TouchPoint(string id)
        {
            try
            {
                long orgSubId = 0;
                if (!long.TryParse(id, out orgSubId))
                    return View("Error");
                if (uRep.isSuperAdministrator(User.Identity.GetUserId()) || uRep.isAdministrator(User.Identity.GetUserId()))
                {
                    OrgSub orgSub = oRep.GetOrgSub(orgSubId, User.Identity.GetUserId());
                    ViewBag.OrgSubName = !string.IsNullOrEmpty(orgSub.ParentOrgSubName) ? orgSub.ParentOrgSubName + " > " + orgSub.RegisteredName : orgSub.RegisteredName;
                    return View("Touchpoint-Admin", oRep.GetTouchpoints(orgSubId, User.Identity.GetUserId()));
                }
                return View("UnAuthorized");
            }
            catch (Exception ex)
            {
                if (ex is UnauthorizedAccessException)
                    return View("UnAuthorized");
                return View("Error");
            }
        }
    }
}

CusExperience/Controllers/PublicController.cs
using CusExperience.CusExperienceService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;

namespace CusExperience.Controllers
{
    public class PublicController : Controller
    {
        SurveyRepositoryClient sRep = new SurveyRepositoryClient();

        [AllowAnonymous]
        public ActionResult PrivacyPolicy()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult IamCXO()
        {
            return View();
        }

         [AllowAnonymous]
        public ActionResult GAAPI()
        {
            return View();
        }

         [AllowAnonymous]
         public ActionResult MapView()
         {
             return View();
         }
       
	}
}

CusExperience/Controllers/SupportController.cs
using CusExperience.CusExperienceService;
using CusExperience.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace CusExperience.Controllers
{
    public class SupportController : Controller
    {
        SupportRepositoryClient spr = new SupportRepositoryClient();

        [AllowAnonymous]
        // GET: Support
        public ActionResult Index(string id)
        {
            if (string.IsNullOrEmpty(id)) return View("Error");

            Support s = spr.GetSupport(id);
            if (s == null) return View("Error");

            return View("~/Views/Support/Customized/" + s.SupportPage + ".cshtml");
        }
    }
}

CusExperience/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Text.RegularExpressions;
using CusExperience.CusExperienceService;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CusExperience.Entities;

namespace CusExperience.Controllers
{
    //[Authorize(Roles = ROLES.ADMINISTRATOR + "," + ROLES.CUSXPPROFESSIONAL)]
    public class SurveyController : Controller
    {
        SurveyRepositoryClient sRep = new SurveyRepositoryClient();
        OrgSubRepositoryClient oRep = new OrgSubRepositoryClient();
        UserRepositoryClient uRep = new UserRepositoryClient();

        public ActionResult Index(string id)
        {
            long orgSubId = 0;
            if (!long.TryParse(id, out orgSubId))
                return View("Error");

            if (uRep.isSuperAdministrator(User.Identity.GetUserId()) || uRep.isAdministrator(User.Identity.GetUserId()))
            {
                OrgSub orgSub = oRep.GetOrgSub(orgSubId, User.Identity.GetUserId());
                ViewBag.OrgSubName = !string.IsNullOrEmpty(orgSub.ParentOrgSubName) ? orgSub.ParentOrgSubName + " > " + orgSub.RegisteredName : orgSub.RegisteredName ;
               return View(sRep.GetSurveysByOrgSub(orgSubId, User.Identity.GetUserId()));
            }
            return View("UnAuthorized");
        }

        public ActionResult OrgSub()
        {
             if (uRep.isSuperAdministrator(User.Identity.GetUserId()))
             {
                 return View(oRep.GetOrgSubs(User.Identity.GetUserId()));
             }
             return View("UnAuthorized");
        }

        public ActionResult Create(string id, string templateName)
        {
            if (uRep.isSuperAdministrator(User.Identity.GetUserId()) || uRep.isAdministrator(User.Identity.GetUserId()))
            {
                long orgSubId = 0;
                if (!long.TryParse(id, out orgSubId))
                    return View("Error");

                OrgSub orgSub = oRep.GetOrgSub(orgSubId, User.Identity.GetUserId());
                ViewBag.OrgSubName = !string.IsNullOrEmpty(orgSub.ParentOrgSubName) ? orgSub.ParentOrgSubName + " > " + orgSub.RegisteredName : orgSub.RegisteredName;

                Survey survey = sRep.GetTemplateSurveyByOrgSub(orgSubId, templateName, User.Identity.GetUserId());
                if (survey == null)
                    return View("Error");
                return View("Detail", survey);
            }
            return View("UnAuthorized");
        }

        public ActionResult Detail(string orgsubid, string surveyid)
        {
            if (uRep.isSuperAdministrator(User.Identity.GetUserId()) || uRep.isAdministrator(User.Identity.GetUserId()))
            {
                int surveyID = 0;
                long orgSubID = 0;

                if (!Int32.TryParse(surveyid, out surveyID) || !Int64.TryParse(orgsubid, out orgSubID))
                    return View("Error");

                OrgSub orgSub = oRep.GetOrgSub(orgSubID, User.Identity.GetUserId());
                ViewBag.OrgSubName = !string.IsNullOrEmpty(orgSub.ParentOrgSubName) ? orgSub.ParentOrgSubName + " > " + orgSub.RegisteredName : orgSub.RegisteredName;

                Survey survey = sRep.GetSurvey(surveyID, User.Identity.GetUserId());

                if (survey == null)
                    return View("Error");
                return View(survey);
            }
            return View("UnAuthorized");
        }

        [AllowAnonymous]
        public ActionResult Publish(string url)
        {
            if (!string.IsNullOrEmpty(url))
            {
                Survey survey = sRep.GetPublishedSurvey(url);
                if (survey == null)
                    return View("Error");
                string surveyTitle = Regex.Replace(survey.SurveyTitle, @"<[^>]+>|;", string.Empty).Trim();
                string surveyTitleNormalised = Regex.Replace(surveyTitle, @"&nbsp", " ").Trim();
                ViewBag.Title = surveyTitleNormalised + " | CusExperience - Your Customers' Experience Feedback Rating Survey";
                if (!string.IsNullOrEmpty(survey.PublishPage))
                    return View("~/Views/Customized/" + survey.PublishPage + ".cshtml", survey);
                return View(survey);
            }
            return View("Error");
        }

        public ActionResult Preview(string id)
        {
            if (uRep.isSuperAdministrator(User.Identity.GetUserId()) || uRep.isAdministrator(User.Identity.GetUserId()) || uRep.isCusXPProfessional(User.Identity.GetUserId()))
            {
                int surveyID = 0;
                if (!Int32.TryParse(id, out surveyID))
                    return View("Error");
                
                Survey survey = sRep.GetSurvey(surveyID, User.Identity.GetUserId());
                if (survey == null)
                    return View("Error");
                ViewBag.Title = "CusExperience - Your Customer Experience";
                return View(survey);
            }
            return View("UnAuthorized");
        }
    }
}

CusExperience/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.EntityFramework;
@using CusExperience.CusExperienceService;
@using System.Security.Principal;
@using CusExperience.Utilities;

@{ 
    var uRep = new UserRepositoryClient();
    long OrgSubID = uRep.GetCurrentUser(User.Identity.GetUserId()).OrgSub.OrgSubID;
  }
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            display: none;
        }
    </style>
    @Styles.Render("~/Content/css") 

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta property="og:image" content="http://cusexperience.com/Images/CusExp.png" />
    <meta property="og:title" content="CusExperience - Your Customer Experience" />

    <meta name="google-site-verification" content="bVp49hDhnateIi6Ns5-L1CIUvWSjCyw21IqLWt6qBQY" />
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-51962624-1', 'auto');
        ga('require', 'displayfeatures');
        ga('send', 'pageview');

    </script>
    
    <title>CusExperience - Your Customers' Experience</title>
    <link href='http://fonts.googleapis.com/css?family=PT+Sans|PT+Sans+Narrow|Roboto:300|Roboto+Condensed:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="@Href("~/Content/Style.css")" />
    <link rel="stylesheet" href="@Href("~/Content/pe-icon-7-stroke.css")" />
    <link rel="stylesheet" href="@Href("~/Content/helper.css")" />
    <link rel="stylesheet" href="@Href("~/Content/ios7-style-font-icons.min.css")" />
    <link rel="stylesheet" href="@Href("~/Content/bootstrap.css")" />
    <link rel="stylesheet" href="@Href("~/Content/bootstrap.min.css")" />
    <link rel="stylesheet" href="@Href("~/Content/ui-lightness/jquery-ui-1.10.4.custom.css")">
    <link rel="stylesheet" href="@Href("~/Content/jquery.multiselect.css")" />
    
    <script src="@Href("~/Scripts/jquery-2.1.1.js")"></script>
    <script src="@Href("~/Scripts/knockout-3.1.0.js")"></script>
    <script src="@Href("~/Scripts/jquery-ui-1.10.4.custom.js")"></script>
    <script src="@Href("~/Scripts/jquery.validate.js")"></script>
    <script src="@Href("~/Scripts/jquery.autosize.min.js")"></script>
    <script src="@Href("~/Scripts/bootstrap.js")"></script>
    <script src="@Href("~/Scripts/jquery.ui.touch-punch.js")"></script>
    <script src="@Href("~/Scripts/jquery.multiselect.min.js")"></script> 
    <script src="@Href("~/Scripts/jquery.mobile.custom.min.js")"></script>
    <script src="@Href("~/Scripts/spin.js")"></script>
    <script src="@Href("~/Scripts/jquery.simplePagination.js")"></script>
    <script src="@Href("~/JS/global.js")"></script>
    <script src="@Href("~/Scripts/html2canvas.js")"></script>
    <script src="@Href("~/JS/Model/constant.js")"></script>
    <script src="@Href("~/JS/support_view.js")"></script>
</head>

<body>
    <!--<div id="overlay"></div>-->
    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--@Html.ActionLink("CusExperience","Index", "Home", null, new { @class = "navbar-brand" })-->   
                <a href="@Url.Action("Index", "Home", null,Request.Url.Scheme)" class="navbar-brand">Cus<b>Experience</b></a>       
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="usermenu">@Html.ActionLink(HttpContext.Current.User.Identity.Name, "UserProfile", "Account")</li>
                    @if (uRep.isSuperAdministrator(User.Identity.GetUserId()))
                    {
                        <li class="createmenu @Html.ActivePage("Home", "Index")">@Html.ActionLink("Create", "OrgSub", "Survey")</li>
                        <li class="adminmenu @Html.ActivePage("OrgSub", "Index")">@Html.ActionLink("Administer", "Index", "OrgSub")</li>
                        <li class="managemenu @Html.ActivePage("Survey", "OrgSub")">@Html.ActionLink("Manage", "OrgSub", "Survey")</li>
                        <li class="analysemenu @Html.ActivePage("Analytics", "OrgSub")">@Html.ActionLink("Analyse", "OrgSub", "Analytics")</li>
                    }
                    @if (uRep.isAdministrator(User.Identity.GetUserId()))
                    {
                        <li class="createmenu @Html.ActivePage("Survey", "Index")">@Html.ActionLink("Create", "Index", "Survey", new { id = OrgSubID }, null)</li>
                        <li class="adminmenu @Html.ActivePage("OrgSub", "Index")">@Html.ActionLink("Administer", "Index", "OrgSub", new { id = OrgSubID }, null)</li>
                        <li class="managemenu @Html.ActivePage("Survey", "Index")">@Html.ActionLink("Manage", "Index", "Survey", new { id = OrgSubID }, null)</li>
                    }
                    @if (uRep.isAdministrator(User.Identity.GetUserId()) || uRep.isCusXPProfessional(User.Identity.GetUserId()) || uRep.isExecutive(User.Identity.GetUserId()) || uRep.isManager(User.Identity.GetUserId()))
                    {
                        <li class="analysemenu @Html.ActivePage(" analytics", "Index" )">@Html.ActionLink("Analyse", "Index", "Analytics", new { id = OrgSubID }, null)</li>
                    }
                    <li class="logoutmenu"><a onclick="logoutSession()">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div id="body-content" class="container-fluid body-content relativeposbody">
        @RenderBody()
        <footer class="footerZIndex">
            <hr />
            <div class="cr-footer">
                <div class="pull-left fifty">
                    <p style=" color: #4c4c4c;">&copy; 2015 <a href="http://cusexperience.com">Cus<b>Experience</b>.com</a> CusXP Pte Ltd. All Rights Reserved. @Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Public")</p>
                </div>
                <div class="pull-right fifty alignright">
                    <p style="text-align:right;">Best viewed on the latest browsers.</p>
                </div>

            </div>
        </footer>
        <div class="issue-footer">
            <a onclick="showSupportView()" ><img src="@Href("~/Images/Support.png")" /></a>
        </div>
    </div>
    <div id="supportDiv">
        @{ Html.RenderPartial("_SupportView"); }
    </div>
</body>
</html>

CusExperience/Views/Shared/_LayoutBeforeLogin.cshtml
@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.EntityFramework;
@using CusExperience.CusExperienceService;
@using System.Security.Principal;

@{ var uRep = new UserRepositoryClient(); }
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>CusExperience - Your Customers' Experience</title>
    <style>
        @@font-face {
            font-family: 'MyriadPro-Light' src: url('../../fonts/MyriadPro-Light.otf') format('opentype');
        }

        @@font-face {
            font-family: 'MyriadPro';
            src: url('../../fonts/MYRIADPRO-REGULAR.otf') format('opentype');
        }

        .large-icon {
            color: #009bdf;
            font-size: xx-large !important;
        }

        .normal-icon {
            color: #009bdf;
            font-size: x-large !important;
        }

        .medium-icon {
            color: #009bdf;
            font-size: large !important;
        }

        .small-icon {
            color: #009bdf;
            font-size: medium !important;
        }
    </style>
    @Styles.Render("~/Content/css")
    <meta property="og:image" content="http://cusexperience.com/Images/CusExp.png" />
    <meta property="og:title" content="CusExperience - Your Customer Experience" />
    <link rel="stylesheet" href="@Href("~/Content/Style.css")" />
    <link rel="stylesheet" href="@Href("~/Content/pe-icon-7-stroke.css")" />
    <link rel="stylesheet" href="@Href("~/Content/helper.css")" />
    <link rel="stylesheet" href="@Href("~/Content/ios7-style-font-icons.min.css")" />
    <link rel="stylesheet" href="@Href("~/Content/bootstrap.css")" />
    <link rel="stylesheet" href="@Href("~/Content/bootstrap.min.css")" />
    <link rel="stylesheet" href="@Href("~/Content/ui-lightness/jquery-ui-1.10.4.custom.css")">
    <link rel="stylesheet" href="@Href("~/Content/jquery.multiselect.css")" />

    <script src="@Href("~/Scripts/jquery-2.1.1.js")"></script>
    <script src="@Href("~/Scripts/knockout-3.1.0.js")"></script>
    <script src="@Href("~/Scripts/jquery-ui-1.10.4.custom.js")"></script>
    <script src="@Href("~/Scripts/jquery.validate.js")"></script>
    <script src="@Href("~/Scripts/jquery.autosize.min.js")"></script>
    <script src="@Href("~/Scripts/bootstrap.js")"></script>
    <script src="@Href("~/Scripts/jquery.ui.touch-punch.js")"></script>
    <script src="@Href("~/Scripts/jquery.multiselect.min.js")"></script>
    <script src="@Href("~/Scripts/jquery.mobile.custom.min.js")"></script>
    <script src="@Href("~/Scripts/spin.js")"></script>
    <script src="@Href("~/Scripts/jquery.simplePagination.js")"></script>
    <script src="@Href("~/JS/global.js")"></script>
    <script src="@Href("~/Scripts/html2canvas.js")"></script>
    <script src="@Href("~/JS/Model/constant.js")"></script>
    <script src="@Href("~/JS/support_view.js")"></script>

</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="" id="headercontainer">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand cusexp-header" href="http://cusexperience.com/#page-top">Cus<b>Experience</b></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse nav-main" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            @Html.ActionLink(HttpContext.Current.User.Identity.Name, "UserProfile", "Account")
                        </li>
                    } 
                    <li class="page-scroll whatmenu">
                        @Html.ActionLink("What", "Index", "Home", null, null, "what", null, null)
                    </li>
                    <li class="page-scroll whymenu">
                        @Html.ActionLink("Why", "Index", "Home", null, null, "why", null, null)
                    </li>
                    <li class="page-scroll howmenu">
                        @Html.ActionLink("How", "Index", "Home", null, null, "how", null, null)
                    </li>
                    <li class="page-scroll wheremenu">
                        @Html.ActionLink("Where", "Index", "Home", null, null, "where", null, null)
                    </li>
                    <li class="page-scroll whenmenu">
                        @Html.ActionLink("When", "Index", "Home", null, null, "when", null, null)
                    </li>
                    <li class="page-scroll whomenu">
                        @Html.ActionLink("Who", "Index", "Home", null, null, "who", null, null)
                    </li>
                    <li class="page-scroll winsmenu">
                        @Html.ActionLink("Wins", "Index", "Home", null, null, "wins", null, null)
                    </li>
                    <li class="page-scroll contactmenu">
                        @Html.ActionLink("Contact", "Index", "Home", null, null, "contact", null, null)
                    </li>
                    @if (!HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        <li class="page-scroll">
                            <a href="@Url.Action("Login", "Account")" class="active isclickable">Login</a>
                        </li>
                    }
                    @if (HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        <li><a onclick="logoutSession()" class="isclickable">Logout</a></li>
                    } 
                </ul>
            </div>
        </div>
    </nav>
    <div id="body-content" class="container-fluid body-content">
        @RenderBody()
        <footer class="footerZIndex">
            <hr />
            <div class="cr-footer">
                <div class="pull-left fifty">
                    <p style="font-family: 'MyriadPro-Light'; color: #4c4c4c;">&copy; 2015 <a href="http://cusexperience.com">Cus<b>Experience</b>.com</a> CusXP Pte Ltd. All Rights Reserved. @Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Public")</p>
                </div>
                <div class="pull-right fifty alignright">
                    <p style="text-align:right;">Best viewed on the latest browsers.</p>
                </div>

            </div>
        </footer>
        <div class="issue-footer">
            <a onclick="showSupportView()" title="Facing a Problem or Have a Solution to suggest?"><img src="@Href("~/Images/Support.png")" /></a>
        </div>
    </div>
    <div id="supportDiv">
        @{ Html.RenderPartial("_SupportView"); }
    </div>
</body>
</html>